//! Handshake frames: `hello`, `auth_response`, `approve`, `deny`.
//!
//! The hello/auth_response pair binds both sides to a shared nonce
//! and proves possession of the private key matching each peer's
//! claimed Device ID. Approve/deny is the user-facing trust gate
//! that fires once mutual auth is verified.

use serde::{Deserialize, Serialize};

use super::rpc::CapabilityAdvert;

/// Sent immediately on channel open by both ends. Carries the
/// sender's claimed Device ID, a random nonce the other side must
/// sign, and an optional capabilities blob. The peer signs the
/// payload built by [`crate::signing::handshake_payload`].
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HelloMessage {
    /// Wire-protocol version. v1 senders MAY omit features the
    /// receiver doesn't advertise; v1 receivers MUST silently drop
    /// unknown message kinds.
    pub protocol: u32,
    /// Bare-pubkey Device ID, base32-lowercase. Display suffix
    /// omitted on the wire — the receiver derives it themselves if
    /// they want to show the peer to the user.
    pub device_id: String,
    /// Self-reported label. Cosmetic; peers cannot rely on labels
    /// for identity.
    #[serde(default)]
    pub label: String,
    /// Random 32-byte challenge, base32-lowercase. The other side
    /// must sign
    /// `SIGN_DOMAIN_TAG || nonce || my_device_id || their_device_id`
    /// (see [`crate::signing::handshake_payload`]) and return the
    /// signature in `auth_response`.
    pub nonce: String,
    /// Short human-readable verification code (6 chars, `[a-z0-9]`)
    /// generated by the sender. Displayed prominently on both sides
    /// during a pending approval so the users can confirm by
    /// out-of-band channel ("hey I'm sending a request, my code is
    /// X") that the request they see is really from the person they
    /// think it is. Not load-bearing — the ed25519 signatures
    /// authenticate identity; this is just the UX anchor.
    pub verification_code: String,
    /// Capabilities the sender advertises. Optional — omitted by
    /// older peers; receivers treat absence as
    /// [`CapabilityAdvert::default`].
    #[serde(default)]
    pub capabilities: Option<CapabilityAdvert>,
    /// Maximum concurrent connections this peer is willing to
    /// maintain. Feeds the topology selector — a peer that says
    /// "I can hold 8" absorbs more of the load when nearby ones
    /// are at the floor. Omitted by older peers; the engine
    /// defaults to 6 when missing.
    #[serde(default)]
    pub max_connections: Option<u32>,
    /// Capability-negotiation list — see [`super::features`]. Older
    /// peers omit; receivers treat absence as an empty list.
    #[serde(default)]
    pub features: Vec<String>,
    /// Sender's app version. Cosmetic only; surfaced in the peer
    /// detail UI so users can see when a peer is on an older /
    /// newer release than them.
    #[serde(default)]
    pub app_version: Option<String>,
}

/// Response to [`HelloMessage`] proving the sender controls the
/// private key matching `HelloMessage::device_id`. The receiver
/// verifies the signature against the peer's pubkey; on failure
/// the connection is torn down without prompting the user.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AuthResponseMessage {
    /// Base32-lowercase signature of the handshake payload (see
    /// [`crate::signing::handshake_payload`]).
    pub signature: String,
}

/// Sent by the local side once the peer is cleared for app traffic:
/// either auto-approved from the roster, or the user clicked
/// "approve" in the network browser. Both sides must observe each
/// other's approve before the connection transitions to ACTIVE.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApproveMessage {}

/// Sent when the local side rejects the peer. The peer should not
/// reconnect until the user approves again (the engine treats this
/// as a hint, not a hard ban — repeated reconnect attempts after a
/// deny just get re-denied, but the user can reverse the decision
/// from the network browser).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DenyMessage {
    #[serde(default)]
    pub reason: Option<String>,
}
